apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-webhook-binarylane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-webhook-binarylane.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cert-manager-webhook-binarylane.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cert-manager-webhook-binarylane.name" . }}
    spec:
      serviceAccountName: {{ include "cert-manager-webhook-binarylane.fullname" . }}
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --secure-port=4443
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName }}
          ports:
            - containerPort: 4443
              name: https
              protocol: TCP
            - containerPort: 6080
              name: healthcheck
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
              scheme: HTTP
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: {{ include "cert-manager-webhook-binarylane.fullname" . }}-tls
