apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-binarylane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-webhook-binarylane.name" . }}
spec:
  ports:
    - port: 443
      targetPort: 4443
      protocol: TCP
      name: https
  selector:
    app: {{ include "cert-manager-webhook-binarylane.name" . }}
  type: {{ .Values.service.type }}
